from . import asosiy
from . import tur
from . import kontakt
from . import viloyatlar
from . import ha_Yoq
from . import viloyatlar_kerak
from . import lokatsiya
from . import kanalga_ulashish
from . import kanalga_ulashish_kerak